// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
..........................................................
11..11..111..11..11....55....111..1.....11.111..1..11..111
1.1.1.1.1...1...1.....5..5....1..1.1...1....1..1.1.1.1..1.
11..11..11...1...1....5555....1..1.1....1...1..111.11...1.
1...1.1.1.....1...1...5..5....1..1.1.....1..1..1.1.1.1..1.
1...1.1.111.11..11....5..5....1...1....11...1..1.1.1.1..1.
..........................................................
`;
            case "image1":
            case "myImage":return img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 d c 
c 2 2 2 2 2 2 2 2 2 2 2 d d c 
c 2 2 2 2 2 2 2 2 2 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`;
            case "image4":
            case "myImage2":return img`
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
. . 8 8 8 8 8 8 8 8 8 8 8 . . 
. 8 6 6 6 6 6 6 6 6 6 6 6 8 . 
8 8 6 6 6 6 6 6 6 6 6 6 6 8 8 
8 6 6 6 6 6 6 6 6 6 6 6 6 6 8 
8 6 6 6 6 6 6 6 6 6 6 6 6 6 8 
8 6 6 6 6 6 6 6 6 6 6 6 6 6 8 
8 6 6 6 6 6 6 6 6 6 6 6 6 9 8 
8 6 6 6 6 6 6 6 6 6 6 6 9 9 8 
8 8 6 6 6 6 6 6 6 6 9 9 9 8 8 
. 8 6 6 6 6 6 9 9 9 9 9 9 8 . 
. . 8 8 8 8 8 8 8 8 8 8 8 . . 
. . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage1":return img`
. . . . . . . . . . . . . . . . 
. . . 1 . . . . . . . . . 1 . . 
. . . 1 1 . . . . . . . 1 . . . 
. . . . 1 1 . . . . . 1 1 . . . 
. . . . . 1 1 . . . . 1 . . . . 
. . . . . . . 1 . . 1 . . . . . 
. . . . . . 1 1 . . 1 1 . . . . 
. . . . 1 . . . . . . . . 1 1 . 
. . . . 1 1 1 . . . . 1 1 1 . . 
. . . . . . 1 1 1 1 1 1 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "Char":return img`
. . . . . . . . . . . . . . . . 
. . . . . 3 . . . . 3 . . . . . 
. . . . . 3 3 . . 3 3 . . . . . 
. . . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 1 3 3 1 3 . . . . . 
. . . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 3 3 3 3 3 . . . . . 
. . . . . . 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . . 
. 3 . 3 3 3 3 3 3 3 3 3 . . . . 
3 . . 3 3 3 3 3 3 3 3 3 3 . . . 
3 . 3 3 3 3 3 3 3 3 3 3 3 . . . 
. 3 . 3 3 3 3 3 3 3 3 3 3 3 . . 
. . 3 3 3 . . 3 3 3 . 3 3 3 . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . . . 8 . . . . 8 . . . . . 
. . . . . 8 8 . . 8 8 . . . . . 
. . . . . 8 8 8 8 8 8 . . . . . 
. . . . . 8 1 8 8 1 8 . . . . . 
. . . . . 8 8 8 8 8 8 . . . . . 
. . . . . 8 8 8 8 8 8 . . . . . 
. . . . . . 8 8 8 8 . . . . . . 
. . . . 8 8 8 8 8 8 8 . . . . . 
. . . . 8 8 8 8 8 8 8 . . . . . 
. 8 . 8 8 8 8 8 8 8 8 8 . . . . 
8 . . 8 8 8 8 8 8 8 8 8 8 . . . 
8 . 8 8 8 8 8 8 8 8 8 8 8 . . . 
. 8 . 8 8 8 8 8 8 8 8 8 8 8 . . 
. . 8 8 8 . . 8 8 8 . 8 8 8 . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. 9 . . . . . . . . . . . . 9 . 
9 9 . 9 . . . . . . . . 9 . 9 9 
9 9 9 9 . . . . . . . . 9 9 9 9 
. . 9 9 9 . . . 9 . . 9 9 9 . . 
. . . . 9 9 9 9 9 9 9 9 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . 9 . . . . . . . . . . . . 
. 9 . 9 . . . . . . . . . 9 . . 
. . 9 . . . . . . . . . . 9 . . 
. . . 9 . . . . . . . . . . . . 
9 . . 9 . . . 9 . . . . 9 . . 9 
9 9 9 . 9 . . 9 . . . . . 9 9 9 
. . 9 9 9 . . . 9 . . 9 9 9 . . 
. . . . 9 9 9 9 9 9 9 9 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . 9 . . . . . . . . . . . . 
. 9 . . . . . . . . . . 9 . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . 9 . . 
. . . . . . . 9 . . . . . 9 . . 
. . . . . . . . . . . . . . . . 
9 9 . . . . . . . . . . . . 9 9 
9 9 9 . . . . . . . . . . 9 9 9 
. . 9 9 9 . . 9 . . . 9 9 9 . . 
. . . . 9 9 9 9 9 9 9 9 . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim0":
            case "anim2":return [img`
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
1 1 1 . 1 . 1 1 1 1 
. . . . 1 . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
. . . . . . . . . . 
`];
            case "myAnim1":
            case "anim3":return [img`
. . . 1 1 . . . 
. . 1 . . 1 . . 
. 1 . 1 . . 1 . 
. . . 1 1 . . . 
. . . 1 1 . . . 
1 1 . 1 1 . 1 1 
1 1 . 1 1 . 1 1 
1 1 1 1 1 1 1 1 
. 1 1 1 1 1 1 . 
. . . 1 1 . . . 
`, img`
. . . . . . . . 
. . . . . . . . 
. . . 1 . . . . 
. 1 . 1 1 . 1 . 
1 . . 1 1 . . 1 
. . . 1 1 . . . 
. 1 . 1 1 . 1 . 
. . 1 . 1 1 . . 
. . . 1 . . . . 
. . . . 1 . . . 
`, img`
. . . . . . . . 
. . . . . . . . 
. . . 1 . . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
1 . . 1 1 . . 1 
. . . . 1 . . . 
. 1 . . . . 1 . 
. . . 1 . . . . 
`, img`
. . . . . . . . 
. . . . . . . . 
. . . 1 . . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . . 1 . . . 
. . . . . . . . 
. . . . . . . . 
`];
            case "myAnim2":
            case "anim4":return [img`
.....................
.....................
.......1111111.......
.....11ccccccc11.....
....1cc2222222cc1....
...1c22222222222c1...
...1c22222222222c1...
..1c2222222222222c1..
..1c2222222222222c1..
..1c2222222222222c1..
..1c2222222222222c1..
..1c222222222222dc1..
..1c22222222222ddc1..
..1c2222222222dddc1..
...1c2222222ddddc1...
...1c222222dddddc1...
....1ccdddddddcc1....
.....11ccccccc11.....
.......1111111.......
.....................
.....................
`, img`
.....................
......1..............
.......1.....1..1....
....1..ccccccc.......
.....cc2222222cc..1..
..1.c22222222222c....
....c22222222222c....
.1.c2222222222222c.1.
...c2222222222222c...
...c2222222222222c...
1..c2222222222222c.1.
...c222222222222dc...
...c22222222222ddc...
.1.c2222222222dddc...
....c2222222ddddc.1..
....c222222dddddc....
..1..ccdddddddcc.1...
.......ccccccc.......
....1....1......1....
......1....1..1......
.....................
`, img`
..........1.......1..
.1...................
.....................
.......ccccccc.......
.....cc2222222cc.....
....c22222222222c....
....c22222222222c....
...c2222222222222c...
...c2222222222222c...
...c2222222222222c..1
...c2222222222222c...
...c222222222222dc...
...c22222222222ddc...
...c2222222222dddc...
1...c2222222ddddc....
....c222222dddddc....
.....ccdddddddcc.....
.......ccccccc.......
.....................
...1...............1.
...........1.........
`, img`
.....................
.....................
.....................
.......ccccccc.......
.....cc2222222cc.....
....c22222222222c....
....c22222222222c....
...c2222222222222c...
...c2222222222222c...
...c2222222222222c...
...c2222222222222c...
...c222222222222dc...
...c22222222222ddc...
...c2222222222dddc...
....c2222222ddddc....
....c222222dddddc....
.....ccdddddddcc.....
.......ccccccc.......
.....................
.....................
.....................
`];
            case "myAnim3":
            case "anim5":return [img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 d c 
c 2 2 2 2 2 2 2 2 2 2 2 d d c 
c 2 2 2 2 2 2 2 2 2 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`, img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 2 f 2 2 2 2 2 d c 
c 2 2 2 2 2 2 2 2 2 2 2 d d c 
c 2 2 2 2 2 2 2 2 2 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`, img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 f 2 2 2 2 2 f 2 2 c . 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 f f f 2 2 2 2 d c 
c 2 2 2 2 2 2 2 2 2 2 2 d d c 
c 2 2 2 2 2 2 2 2 2 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`, img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 f 2 2 2 2 2 f 2 2 c . 
c 2 2 2 2 f 2 2 2 f 2 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 f f f 2 2 2 2 d c 
c 2 2 2 2 f 2 2 2 f 2 2 d d c 
c 2 2 2 2 2 2 2 2 2 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`, img`
. . . . c c c c c c c . . . . 
. . c c 2 2 2 2 2 2 2 c c . . 
. c 2 2 2 2 2 2 2 2 2 2 2 c . 
. c 2 2 f 2 2 2 2 2 f 2 2 c . 
c 2 2 2 2 f 2 2 2 f 2 2 2 2 c 
c 2 2 2 f 2 f 2 f 2 f 2 2 2 c 
c 2 2 2 f 2 2 2 2 2 f 2 2 2 c 
c 2 2 2 2 2 2 2 2 2 2 2 2 2 c 
c 2 2 2 2 2 f f f 2 2 2 2 d c 
c 2 2 2 2 f 2 2 2 f 2 2 d d c 
c 2 2 2 2 f 2 2 2 f 2 d d d c 
. c 2 2 2 2 2 2 2 d d d d c . 
. c 2 2 2 2 2 2 d d d d d c . 
. . c c d d d d d d d c c . . 
. . . . c c c c c c c . . . . 
`];
            case "myAnim5":
            case "anim7":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
            case "myAnim6":
            case "anim8":return [img`
. . . . . . . . . . . . . . . 
. . . . 3 . . . . 3 . . . . . 
. . . . 3 3 . . 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 1 3 3 1 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . 
. . . 3 3 3 3 3 3 3 3 . . . . 
. 3 . 3 3 3 3 3 3 3 3 3 . . . 
3 . . 3 3 3 3 3 3 3 3 3 3 . . 
3 . 3 3 3 3 3 3 3 3 3 3 3 . . 
. 3 . 3 3 3 3 3 3 3 3 3 3 3 . 
. . 3 3 3 . . 3 3 3 . 3 3 3 . 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . 3 . . . . 3 . . . . . 
. . . . 3 3 . . 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 3 3 3 1 3 . . . . . 
. . . . 3 1 3 3 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . 
. . . . 3 3 3 3 3 3 3 3 . . . 
. 3 . 3 3 3 3 3 3 3 3 3 . . . 
3 . . 3 3 3 3 3 3 3 3 3 3 . . 
3 . 3 3 3 3 3 3 3 3 3 3 3 . . 
. 3 . 3 3 3 3 3 3 3 3 3 3 3 . 
. . . 3 3 3 . . 3 3 3 . 3 3 3 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . 3 . . . . 3 . . . . . 
. . . . 3 3 . . 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 1 3 3 1 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . 
. . . . 3 3 3 3 3 3 3 3 . . . 
3 . . 3 3 3 3 3 3 3 3 3 . . . 
3 . . 3 3 3 3 3 3 3 3 3 3 . . 
3 . 3 3 3 3 3 3 3 3 3 3 3 . . 
. 3 . 3 3 3 3 3 3 3 3 3 3 3 . 
. . 3 . 3 3 3 3 . . 3 3 . 3 3 
. . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . 
. . . . 3 . . . . 3 . . . . . 
. . . . 3 3 . . 3 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . 3 1 3 3 3 3 . . . . . 
. . . . 3 3 3 3 1 3 . . . . . 
. . . . 3 3 3 3 3 3 . . . . . 
. . . . . 3 3 3 3 . . . . . . 
. . . . 3 3 3 3 3 3 3 . . . . 
. . . 3 3 3 3 3 3 3 3 . . . . 
3 . . 3 3 3 3 3 3 3 3 3 . . . 
3 . . 3 3 3 3 3 3 3 3 3 3 . . 
3 . 3 3 3 3 3 3 3 3 3 3 3 . . 
. 3 . 3 3 3 3 3 3 3 3 3 3 3 . 
. . 3 3 . 3 3 3 3 . . 3 3 . 3 
. . . . . . . . . . . . . . . 
`];
            case "myAnim7":
            case "anim9":return [img`
. . . . . . . . . . . . . . . . 
. . . . . 9 . . . . 9 . . . . . 
. . . . . 9 9 . . 9 9 . . . . . 
. . . . . 9 1 9 9 1 9 . . . . . 
. . . . . 9 1 9 9 1 9 . . . . . 
. . . . . 9 9 9 9 9 9 . . . . . 
. . . . . 9 9 9 9 9 9 . . . . . 
. . . . . . 9 9 9 9 . . . . . . 
. . . . 9 9 9 9 9 9 9 . . . . . 
. . . . 9 9 9 9 9 9 9 . . . . . 
. 9 . 9 9 9 9 9 9 9 9 9 . . . . 
9 . . 9 9 9 9 9 9 9 9 9 9 . . . 
9 . 9 9 9 9 9 9 9 9 9 9 9 . . . 
. 9 . 9 9 9 9 9 9 9 9 9 9 9 . . 
. . 9 9 9 . . 9 9 9 . 9 9 9 . . 
. . . . . . . . . . . . . . . . 
`, img`
. . . . . . . . . . . . . . . . 
. . . . . 6 . . . . 6 . . . . . 
. . . . . 6 6 . . 6 6 . . . . . 
. . . . . 6 1 6 6 1 6 . . . . . 
. . . . . 6 1 6 6 1 6 . . . . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . 6 6 6 6 6 6 . . . . . 
. . . . . . 6 6 6 6 . . . . . . 
. . . . 6 6 6 6 6 6 6 . . . . . 
. . . . 6 6 6 6 6 6 6 . . . . . 
. 6 . 6 6 6 6 6 6 6 6 6 . . . . 
6 . . 6 6 6 6 6 6 6 6 6 6 . . . 
6 . 6 6 6 6 6 6 6 6 6 6 6 . . . 
. 6 . 6 6 6 6 6 6 6 6 6 6 6 . . 
. . 6 6 6 . . 6 6 6 . 6 6 6 . . 
. . . . . . . . . . . . . . . . 
`];
            case "bulletBoom":
            case "anim10":return [img`
. . . . . . . . 
. . . . . . . . 
. . . 1 . . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . 1 1 . . . 
. . . . 1 . . . 
. . . . . . . . 
. . . . . . . . 
`, img`
. . . . . . . . 
. . . . . . . . 
. . . 1 . 1 . . 
. 1 . . . . . . 
. . . 1 . 1 . . 
. . 1 . 1 . . . 
. . . 1 . 1 . . 
. . . . 1 . . . 
. . . . . . . . 
. . . . . . . . 
`, img`
. . . . . . . . 
. . 1 . . . 1 . 
. . . . . . . . 
. 1 . . . . . . 
. . . . . 1 . . 
. . 1 . . . . . 
. . . . . . . . 
. . 1 . 1 . . . 
. . . . . . 1 . 
. . . . . . . . 
`, img`
. . . 1 . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . 1 
. . . . . . . . 
. . . . . . . . 
1 . . . . . . . 
. . . . . . . . 
. . . . . . 1 . 
. . . . . . . . 
`, img`
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
. . . . . . . . 
`];
            case "DefaultBoss":
            case "anim6":return [img`
........................................
........................................
........................................
........................................
.......eeeeeeeeeeeeee...................
.......eeeeeeeeeeeeeeee.................
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
.......eeeeeeeeeeeeeeeececeeeeeee.......
.......eeeeececeeeeeeeccccceeeeee.......
.......eeeeccccceeeeeeeccceeeeeee.......
......eeeeeeccceeeeeeeccccceeeeee.......
......eeeeeccccceeeeeeececeeeeeee.......
.....eeeeeeececeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeecceeeeceeecceeeeee.......
........eeeeecceceeeccceceeceeeee.......
........eeeeeceecccceecceeeeceeee.......
........eeeeeeeeeeceeeeeeeeeeeeee.......
........eeeeeeeeeeeeeeeeeeeeeeeee.......
........eeeeeeeeeeeeeeeeeeeeeeeee.......
.........eeeeeeeeeeeeeeeeeeeeeeee.......
...........eeeeeeeeeeeeeeeeeeeee........
................eeeeeeeeeeeeee..........
..................eeeeee................
........................................
........................................
........................................
........................................
........................................
`, img`
........................................
........................................
........................................
........................................
.......eeeeeee..........................
.......eeeeeeeee.....eeeeeeee...........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
.......eeeeeeeeeeeeeeeececeeeeeee.......
.......eeeeececeeeeeeeccccceeeeee.......
.......eeeeccccceeeeeeeccceeeeeee.......
......eeeeeeccceeeeeeeccccceeeeee.......
......eeeeeccccceeeeeeececeeeeeee.......
......eeeeeececeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeecceeeeceeecceeeeee.......
........eeeeecceceeeccceceeceeeee.......
........eeeeeceecccceecceeeeceeee.......
........eeeeeeeeeeceeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeee............
.......eeeeeeeeeeeeeeeeeeeee............
........eeeeeee.....eeee................
.........ee.............................
........................................
........................................
........................................
........................................
`, img`
........................................
........................................
........................................
.......................eeeeeee..........
................eeeeeeeeeeeeee..........
...........eeeeeeeeeeeeeeeeeee..........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeecececeeeeeeeeeeeeeeeee.......
......eeeeeeccceeeeeeecececeeeeee.......
.......eeeeccccceeeeeeeccceeeeeeee......
......eeeeeeccceeeeeeeccccceeeeeee......
......eeeeecececeeeeeeeccceeeeeeee......
......eeeeeeeeeeeeeeeecececeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeecceeeeceeecceeeeee.......
.......eeeeeecceceeeccceceeceeeee.......
.......eeeeeeceecccceecceeeeceeee.......
.......eeeeeeeeeeeceeeeeeeeeeeee........
........eeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeeeeeeeeeeeeeeeeee.........
........eeeeeeeeeeeeeeeeeeeeee..........
........eeeeeeeeeeeeeeeeee..............
........eeeeeeeeeeeeeee.................
.........eeeeeeeeeeeeee.................
..........eeeeeeeeeeeee.................
............eeeee.......................
........................................
........................................
........................................
`, img`
........................................
........................................
........................................
........................................
.......eeeeeee..........................
.......eeeeeeeee.....eeeeeeee...........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
.......eeeecececeeeeeeeeeeeeeeeee.......
.......eeeeeccceeeeeeecececeeeeee.......
.......eeeeccccceeeeeeeccceeeeeee.......
......eeeeeeccceeeeeeeccccceeeeee.......
......eeeeecececeeeeeeeccceeeeeee.......
......eeeeeeeeeeeeeeeecececeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeecceeeeceeecceeeeee.......
........eeeeecceceeeccceceeceeeee.......
........eeeeeceecccceecceeeeceeee.......
........eeeeeeeeeeceeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeee............
.......eeeeeeeeeeeeeeeeeeeee............
........eeeeeee.....eeee................
.........ee.............................
........................................
........................................
........................................
........................................
`];
            case "myAnim8":
            case "anim11":return [img`
........................................
........................................
........................................
........................................
.......eeeeeeeeeeeeee...................
.......eeeeeeeeeeeeeeee.................
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
.......eeeeeeeeeeeeeeeececeeeeeee.......
.......eeeeececeeeeeeeccccceeeeee.......
.......eeeeccccceeeeeeeccceeeeeee.......
......eeeeeeccceeeeeeeccccceeeeee.......
......eeeeeccccceeeeeeececeeeeeee.......
.....eeeeeeececeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeecceeeeceeecceeeeee.......
........eeeeecceceeeccceceeceeeee.......
........eeeeeceecccceecceeeeceeee.......
........eeeeeeeeeeceeeeeeeeeeeeee.......
........eeeeeeeeeeeeeeeeeeeeeeeee.......
........eeeeeeeeeeeeeeeeeeeeeeeee.......
.........eeeeeeeeeeeeeeeeeeeeeeee.......
...........eeeeeeeeeeeeeeeeeeeee........
................eeeeeeeeeeeeee..........
..................eeeeee................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
`, img`
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
.......................eeeeeee..........
................eeeeeeeeeeeeee..........
...........eeeeeeeeeeeeeeeeeee..........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeceeeeeeeeeeeeeeeeeeee......
......eeeeeeeeceeeeeeeeeceeeeeeeee......
......eeeeecececeeeeeeeceeeeeeeee.......
......eeeeeeccceceeeeecececeeeeee.......
.......eeeeccccceeeeececcceeeeeeee......
......eeeeeeccceeeeeeeccccceeeeeee......
......eeeeecececeeeeeeeccceeeeeeee......
......eeeeeeeeeeeeeeeecececeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeecccccceeeeeeee........
.......eeeeeeeeeccceeeecccceeeee........
.......eeeeeeeccceeeeeeeeeceeeeee.......
.......eeeeeeceeeeeeeeeeeeeceeeee.......
.......eeeeeeceeeeeeeeeeeeeeceeee.......
.......eeeeeecceeeeeeeeeeeeceeee........
........eeeeeecccceeeeccccceeeee........
........eeeeeeeeeeccccceeeeeeee.........
........eeeeeeeeeeeeeeeeeeeeee..........
........eeeeeeeeeeeeeeeeee..............
........eeeeeeeeeeeeeee.................
.........eeeeeeeeeeeeee.................
..........eeeeeeeeeeeee.................
............eeeee.......................
`, img`
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
.......................eeeeeee..........
................eeeeeeeeeeeeee..........
...........eeeeeeeeeeeeeeeeeee..........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
.....eeeeeeeeceeeeeeeeeeeeeeeeeeee......
......eeeeeeeeceeeeeeeeeceeeeeeeee......
......eeeeecececeeeeeeeceeeeeeeee.......
......eeeeeeccceceeeeecececeeeeee.......
.......eeeeccccceeeeececcceeeeeeee......
......eeeeeeccceeeeeeeccccceeeeeee......
......eeeeecececeeeeeeeccceeeeeeee......
......eeeeeeeeeeeeeeeecececeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeeeeeeeeeeeeeeee........
......eeeeeeeeeeeecccccceeeeeeee........
.......eeeeeeeeeccceeeecccceeeee........
.......eeeeeeeccceeeeeeeeeceeeeee.......
.......eeeeeeceeeeeeeeeeeeeceeeee.......
.......eeeeeeceeeeeeeeeeeeeeceeee.......
.......eeeeeecceeeeeeeeeeeeceeee........
........eeeeeecccceeeeccccceeeee........
........eeeeeeeeeeccccceeeeeeee.........
........eeeeeeeeeeeeeeeeeeeeee..........
........eeeeeeeeeeeeeeeeee..............
........eeeeeeeeeeeeeee.................
.........eeeeeeeeeeeeee.................
..........eeeeeeeeeeeee.................
............eeeee.......................
........................................
`, img`
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
.......eeeeeee..........................
.......eeeeeeeee.....eeeeeeee...........
......eeeeeeeeeeeeeeeeeeeeeeee..........
.....eeeeeeeeeeeeeeeeeeeeeeeeeee........
.....eeeeeeeeeeeeeeeeeeeeeeeeeeee.......
.....eeeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
......eeeeeeeeeeeeeeeeeeeeeeeeeeee......
.......eeeecececeeeeeeeeeeeeeeeee.......
.......eeeeeccceeeeeeecececeeeeee.......
.......eeeeccccceeeeeeeccceeeeeee.......
......eeeeeeccceeeeeeeccccceeeeee.......
......eeeeecececeeeeeeeccceeeeeee.......
......eeeeeeeeeeeeeeeecececeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeeee.......
......eeeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeeeeeee........
........eeeeeeecceeeeceeecceeeeee.......
........eeeeecceceeeccceceeceeeee.......
........eeeeeceecccceecceeeeceeee.......
........eeeeeeeeeeceeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeeee.......
.......eeeeeeeeeeeeeeeeeeeeeeeee........
.......eeeeeeeeeeeeeeeeeeeee............
.......eeeeeeeeeeeeeeeeeeeee............
........eeeeeee.....eeee................
.........ee.............................
........................................
........................................
........................................
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
